
- block:
  - name: install vault
    include_tasks: install_vault_ssl.yml
    when: vault.ssl == true
  - name: install vault
    include_tasks: install_vault.yml
    when: vault.ssl != true
  - name: add new key / value pairs to dict
    set_fact:
      ipaddr: "{{ ipaddr | combine({item.key: item.value}) }}"
    with_items:
    - { key: '{{ vault.domen }}', value: '{{ ansible_host }}' }
    delegate_to: "{{ groups['vpn'][0] }}"
    run_once: true
    when: inventory_hostname in groups['vault']
  when: inventory_hostname in groups['vault']
