- name: Create certs
  shell:
    cmd: ./easyrsa build-client-full {{ item }} nopass
    chdir: /etc/openvpn/easy-rsa/
  loop: "{{ ipaddr_list }}"

- name: Creates directory
  file:
      path: /etc/openvpn/clients/{{ item }}
      state: directory
  loop: "{{ ipaddr_list }}"
- name: Copy server certs
  shell: 
    cmd: "cp /etc/openvpn/easy-rsa/pki/ca.crt /etc/openvpn/clients/{{ item }}/ca.crt | cp /etc/openvpn/easy-rsa/pki/ta.key /etc/openvpn/clients/{{ item }}/ta.key "
  loop: "{{  ipaddr_list }}"
  vars: 
    ansible_become: yes
- name: Copy client certs
  shell:
    cmd: "cp /etc/openvpn/easy-rsa/pki/issued/{{ item }}.crt /etc/openvpn/clients/{{ item }}/client.crt | cp /etc/openvpn/easy-rsa/pki/private/{{ item }}.key /etc/openvpn/clients/{{ item }}/client.key"
  loop: "{{  ipaddr_list }}"
  vars: 
    ansible_become: yes
- name: Create client.conf  
  template: 
      src: client.conf.j2
      dest: /etc/openvpn/clients/{{ item }}/client.conf
  loop: "{{ ipaddr_list }}"
  vars: 
     
     ansible_become: yes


- name: Create arhive
  community.general.archive:
    path: /etc/openvpn/clients/{{ item }}/*
    dest: /etc/openvpn/clients/{{ item }}.tgz
  loop: "{{ ipaddr_list }}"
  vars: 
    ansible_become: yes
- name: Copy arhive to localhost 
  fetch: 
    src: /etc/openvpn/clients/{{ item }}.tgz
    dest: ./clients_openvpn/
  loop: "{{ ipaddr_list }}"
  vars: 
    ansible_become: yes

# - name: Copy files to hosts  
#   include_tasks: copy_certs.yml
#   args:
#     apply:
#       delegate_to: "root@{{ item }}"
#   loop: "{{ ipaddr_list | reject('search','{{ ipaddr.vpn }}') | list }}" 

- name: Copy files to hosts  
  include_tasks: copy_certs.yml
  args:
    apply:
      delegate_to: "{{ item }}"
  loop: "{{ groups.vpn_clients }}" 
