- block: 

  - name: start prerun
    include_tasks: "./prerun.yml"
  - name: "Start"
    include_tasks: create_certs_service.yml
    when: list_is_empty
  - name: create vpn users
    include_tasks: create_client.yml
    when: inventory_hostname in groups['vpn']

  - name: Create static ip
    template:
      src: "{{ item.src }}"
      dest: "{{ item.dest }}"
    loop:
      - { 
          src: ipp.txt.j2,
          dest: /etc/openvpn/ipp.txt
        }
      - { 
          src: server.conf.j2, 
          dest: /etc/openvpn/server.conf
        }
  - name: Restart 
    systemd:
      name: openvpn@server
      state: restarted
      enabled: yes
  when: inventory_hostname in groups['vpn']


 

