# - name: add new key / value pairs to dict
#   set_fact:
#       ipaddr: "{{ ipaddr | combine({item.key: item.value}) }}"
#   with_items:
#     - { key: '{{ defectdojo.domen }}', value: '77.232.132.99' }
#     - { key: '{{ vault.domen }}', value: '213.226.100.158' }
#     - { key: '{{ onedev.domen }}', value: '213.226.100.158' }
#     - { key: 'dns', value: '213.226.100.158' }
#     - { key: 'vpn', value: '213.226.100.158' }

- name: Creates directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "/home/{{ ansible_user }}/vpn"

- name: Copy python scrypt 
  copy: 
    src: scrypt.py
    dest: "/home/{{ ansible_user }}/vpn"

- name: run scrypt 
  shell:
    cmd: python3 ./scrypt.py {{ defectdojo.domen }} {{ ipaddr[defectdojo.domen] }} {{ onedev.domen }} {{ ipaddr[onedev.domen] }} vpn {{ ipaddr.vpn }} dns {{ ipaddr.dns }}  {{ vault.domen }} {{ ipaddr[vault.domen] }}
    chdir: /home/{{ ansible_user }}/vpn
  with_items:
  -  "{{ ipaddr }}"
  register: result
- name: debug
  debug:
    msg: "{{ result }}"
- name: set ipaddr
  set_fact:
    ipaddr_list: "{{ result.results[0].stdout_lines[1] }}"
- name: set vpn_ips
  set_fact:
    vpn_ips: "{{ result.results[0].stdout_lines[0] }}"
- name: set map_ip
  set_fact:
    map_ip: "{{ result.results[0].stdout_lines[2] }}"
- name: Check if list is empty
  set_fact:
    list_is_empty: "{{ ipaddr_list | length != 0 }}"
