- name: Copy scrypt
  template:
    src: create_users.sh.j2
    dest: /etc/wireguard/create.sh
- name: create conf
  shell:  
    cmd: "bash /etc/wireguard/create.sh client {{ item }}"
  loop: "{{ vpn.client_users }}"
- name: Create arhive
  community.general.archive:
    path: /etc/wireguard/clients/{{ item }}
    dest: /etc/openvpn/clients/{{ item }}.tgz
  loop: "{{ vpn.client_users }}"
  vars: 
    ansible_become: yes
- name: Copy arhive to localhost 
  fetch: 
    src: /etc/openvpn/clients/{{ item }}.tgz
    dest: ./clients_wg/
  loop: "{{ vpn.client_users }}"
  vars: 
    ansible_become: yes


