
- name: install
  shell:
    cmd: "{{ item }}"
  loop:
    - sysctl -w net.ipv4.ip_forward=1
    - mkdir -p /etc/wireguard/server/ips/
    - mkdir -p /etc/wireguard/server/publickey/
    - mkdir -p /etc/wireguard/server/privatekey/
    - touch /etc/wireguard/server/ips/ips.txt
    - wg genkey |  tee /etc/wireguard/server/publickey/server_private.key | wg pubkey |  tee /etc/wireguard/server/publickey/server_public.key
  vars:
    ansible_become: yes
- name: register pubkey 
  shell:
    cmd: cat /etc/wireguard/server/publickey/server_public.key
  register: pubkey
- name: register privkey 
  shell:
    cmd: cat /etc/wireguard/server/publickey/server_private.key
  register: privkey
- name: Create server.conf  
  template: 
      src: wg_server.conf.j2
      dest: /etc/wireguard/wg0.conf
- name: start
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: restarted
    enabled: yes
# - name: Conifure iptables
#   shell: 
#     cmd: "{{ item }}"
#   loop: 
#     - iptables -A INPUT -i {{ ansible_default_ipv4.interface }} -p tcp --dport 22 -j ACCEPT
#     - iptables -A INPUT -i {{ ansible_default_ipv4.interface }} -p tcp --dport 51820 -j ACCEPT
#     - iptables -A INPUT -i {{ ansible_default_ipv4.interface }} -j DROP
