# - name: Run tasks/other.yaml instead of 'main'
#   ansible.builtin.include_role:
#     name: ../preinstall
# - name: create vpn 
#   include_tasks: install_onedev.yml
#   when: inventory_hostname in groups['onedev']
# - name: Pause for 5 minutes to build app cache
#   ansible.builtin.pause:
#     minutes: 3
# - name: create agents
#   include_tasks: create_agents.yml
#   when: inventory_hostname in groups['onedev_agents']
- name: echo
  debug:
    msg: "{{ ipaddr }}"

- name: add new key / value pairs to dict
  set_fact:
    ipaddr: "{{ ipaddr | combine({item.key: item.value}) }}"
  with_items:
  - { key: 'onedev', value: '{{ ansible_host }}' }
  delegate_to: "{{ groups['vpn'][0] }}"
  run_once: true
  when: inventory_hostname in groups['onedev']
  