- name: Git checkout
  ansible.builtin.git:
    repo: 'https://github.com/prometheus/prometheus.git'
    dest: /home/{{ ansible_user }}/prometheus
    force: true
# - name: Get certs
#   include_tasks: ./get_certs.yml
#   when: defectdojo.ssl != False

- name: Creates directory
  file:
      path: "{{ item }}"
      state: directory
  with_items:
      - "/home/{{ ansible_user }}/prometheus/grafana"
      - "/home/{{ ansible_user }}/prometheus/prometheus"
      - "/home/{{ ansible_user }}/prometheus/alertmanager"
- name: Create docker letscrypt
  template: 
       src: "{{ item.name }}"
       dest: "{{ item.dest }}"
  loop:
     - { name: 'nginx.conf.j2' ,
         dest: '/etc/nginx/conf.d/{{ prometheus.domen }}.conf_ssl' 
       }
     - { name: 'conf.d.j2' ,
         dest: '/etc/nginx/conf.d/{{ prometheus.domen }}.conf' 
       }
     - { name: 'config.monitoring.j2',
         dest: '/home/{{ ansible_user }}/prometheus/grafana/config.monitoring'
       }
     - { name: 'prometheus.yml.j2',
         dest: '/home/{{ ansible_user }}/prometheus/prometheus/prometheus.yml'
       }
     - { name: 'alerts.rules.j2',
         dest: '/home/{{ ansible_user }}/prometheus/prometheus/alerts.rules'
       }
     - { name: 'alertmanager.conf.j2',
         dest: '/home/{{ ansible_user }}/prometheus/alertmanager/config.yml'
       } 

- name: Build and Run
  shell:
    cmd: "{{ item }}"
    chdir: /home/{{ ansible_user }}/prometheus
  loop:
    - docker-compose up --build -d
- name: Start certbot
  shell:
      cmd: "{{ item }}"
  loop:
      - nginx -t && nginx -s reload
      - certbot --nginx -d {{ prometheus.domen }} -m {{ prometheus.email }} --non-interactive --agree-tos
      - certbot --nginx -d {{ prometheus.alert.domen }} -m {{ prometheus.email }} --non-interactive --agree-tos
      - certbot --nginx -d {{ prometheus.grafana.domen }} -m {{ prometheus.email }} --non-interactive --agree-tos
      - certbot --nginx -d {{ prometheus.exporter.domen }} -m {{ prometheus.email }} --non-interactive --agree-tos

# - name: re
#   shell:
#       cmd: "sed -i '1,13 s#}#include /etc/nginx/conf.d/{{ prometheus.domen }}.conf_ssl; }#' /etc/nginx/conf.d/{{ prometheus.domen }}.conf"
