
- name: install 
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker.io
    - docker-compose
    - git
    - curl
    - iptables
    - nginx
    - certbot
    - python3-certbot-nginx
    - openvpn
    - easy-rsa
    - openresolv
    - wireguard
    - resolvconf
  vars:
    ansible_become: yes

