- name: Git checkout defectdojo
  ansible.builtin.git:
    repo: 'https://github.com/DefectDojo/django-DefectDojo.git'
    dest: /home/{{ server_username }}/config/defectdojo
  when: inventory_hostname in groups['defectdojo']

- name: Copy defectdojo files for GitLab server
  templates:
        src: "docker-compose.yml.j2"
        dest: "/home/{{ server_username }}/config/defectdojo/docker-compose.yml"
        mode: '0600'
        owner: root
        group: root
  when: inventory_hostname in groups['defectdojo']
- name: Up defectdojo
  ansible.builtin.shell: /home/{{ server_username }}/config/defectdojo/dc-up-d.sh postgres-redis
  args:
        chdir: "/home/{{ server_username }}/config/defectdojo/"
  ignore_errors: true
  when: inventory_hostname in groups['defectdojo']